---
# vars file for ospf-single-area
# make sure to use the correct interface,Not allow update
routers:
  R1:
    addresses:
      - interface: ether2
        address: 10.10.10.1/30
      - interface: ether6
        address: 50.50.50.1/30
      - interface: ether5
        address: 40.40.40.1/30
      - interface: ether8
        address: 192.168.1.254/24
    ospf:
      instance_name: R1_inst
      area_name: Area_1
      interface_template:
        - interface: ether2
          type: ptp
          passive: false
          cost: 10
          area: Area_1
        - interface: ether6
          type: ptp
          passive: false
          cost: 10
          area: Area_1
        - interface: ether5
          type: ptp
          passive: false
          cost: 10
          area: Area_1
        - interface: ether8
          type: broadcast
          passive: true
          cost: 10
          area: Area_1

  R2:
    addresses:
      - interface: ether2
        address: 10.10.10.2/30
      - interface: ether7
        address: 60.60.60.1/30
      - interface: ether5
        address: 20.20.20.1/30
      - interface: ether8
        address: 192.168.2.254/24
    ospf:
      instance_name: R1_inst
      area_name: Area_1
      interface_template:
        - interface: ether2
          type: ptp
          passive: false
          cost: 10
          area: Area_1
        - interface: ether7
          type: ptp
          passive: false
          cost: 10
          area: Area_1
        - interface: ether5
          type: ptp
          passive: false
          cost: 10
          area: Area_1
        - interface: ether8
          type: broadcast
          passive: true
          cost: 10
          area: Area_1

  R3:
    addresses:
      - interface: ether3
        address: 20.20.20.2/30
      - interface: ether6
        address: 50.50.50.2/30
      - interface: ether4
        address: 30.30.30.1/30
      - interface: ether8
        address: 192.168.3.254/24
    ospf:
      instance_name: R1_inst
      area_name: Area_1
      interface_template:
        - interface: ether3
          type: ptp
          passive: false
          cost: 10
          area: Area_1
        - interface: ether6
          type: ptp
          passive: false
          cost: 10
          area: Area_1
        - interface: ether4
          type: ptp
          passive: false
          cost: 10
          area: Area_1
        - interface: ether8
          type: broadcast
          passive: true
          cost: 10
          area: Area_1

  R4:
    addresses:
      - interface: ether4
        address: 30.30.30.2/30
      - interface: ether7
        address: 60.60.60.2/30
      - interface: ether5
        address: 40.40.40.2/30
      - interface: ether8
        address: 192.168.4.254/24
    ospf:
      instance_name: R1_inst
      area_name: Area_1
      interface_template:
        - interface: ether4
          type: ptp
          passive: false
          cost: 10
          area: Area_1
        - interface: ether6
          type: ptp
          passive: false
          cost: 10
          area: Area_1
        - interface: ether3
          type: ptp
          passive: false
          cost: 10
          area: Area_1
        - interface: ether8
          type: broadcast
          passive: true
          cost: 10
          area: Area_1
