---
# tasks file for ospf-single-area

- name: Deploy to bastion configure
  hosts: routers
  gather_facts: false
  module_defaults:
    group/community.routeros.api:
      hostname: '{{ hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      tls: false
      validate_certs: false
      validate_cert_hostname: false
  tasks:
    - name: Include vars from group_vars
      include_vars: "../group_vars/all.yml"
      no_log: true

    - name: Test ping module
      ansible.builtin.ping:
