- name: "Find And Modify IP address from {{ inventory_hostname }}"
  community.routeros.api_find_and_modify:
    hostname: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    path: "ip address"
    find:
      interface: "{{ interface }}"
    values:
      address: "{{ address }}"
  register: result
  failed_when: result.failed
  no_log: true

- name: "Add IP address to {{ inventory_hostname }}"
  community.routeros.api:
    hostname: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    path: "ip address"
    add: "address={{ address }} interface={{ interface }}"
  when: result.match_count == 0
  no_log: true
